# Generated by Django 4.2.5 on 2023-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister',
            name='client_bussiness_file',
            field=models.ImageField(default='', upload_to='client\x0ciles'),
        ),
    ]
