# Generated by Django 4.2.5 on 2023-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0006_taskassign_ta_accept_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregister',
            name='work_reg_status',
            field=models.IntegerField(default=0),
        ),
    ]
