# Generated by Django 4.2.5 on 2023-10-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0008_leadfield_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfield_register',
            old_name='task_discription',
            new_name='field_discription',
        ),
    ]
