# Generated by Django 4.2.5 on 2023-10-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0009_rename_task_discription_leadfield_register_field_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='leave_request_file',
            field=models.FileField(default='', upload_to='leave\\files'),
        ),
    ]
