# Generated by Django 4.2.3 on 2023-11-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0010_employeeleave_leave_request_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('lead_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_add_date', models.DateField(auto_now=True, null=True)),
                ('lead_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('waste_data', models.IntegerField(default=0)),
                ('lead_status', models.IntegerField(default=0)),
                ('lead_transfer_date', models.DateField(null=True)),
                ('lead_transfer_status', models.IntegerField(default=0)),
                ('lead_collect_Emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('lead_work_regId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.workregister')),
            ],
        ),
        migrations.CreateModel(
            name='lead_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_field_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_field_data', models.CharField(blank=True, default='', max_length=855, null=True)),
                ('leadId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
    ]
