# Generated by Django 4.2.3 on 2023-11-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Clients_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Update_Action', models.IntegerField(default=0)),
                ('Assign_Action', models.IntegerField(default=0)),
                ('Client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.data')),
                ('emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
            ],
        ),
    ]
