# Generated by Django 4.2.3 on 2023-11-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients_assign',
            old_name='Client',
            new_name='data',
        ),
    ]
