# Generated by Django 4.2.3 on 2023-11-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0010_employeeleave_leave_request_file'),
        ('Telecaller', '0002_rename_client_clients_assign_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_assign_for_TC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Update_Action', models.IntegerField(default=0)),
                ('Assign_Action', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='lead_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_field_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_field_data', models.CharField(blank=True, default='', max_length=855, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('lead_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lead_add_date', models.DateField(auto_now=True, null=True)),
                ('lead_add_time', models.TimeField(auto_now_add=True, null=True)),
                ('waste_data', models.IntegerField(default=0)),
                ('lead_status', models.IntegerField(default=0)),
                ('lead_transfer_date', models.DateField(null=True)),
                ('lead_transfer_status', models.IntegerField(default=0)),
                ('lead_collect_Emp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('lead_work_regId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.workregister')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients_assign',
            name='data',
        ),
        migrations.RemoveField(
            model_name='clients_assign',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Client',
        ),
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.DeleteModel(
            name='Clients_assign',
        ),
        migrations.DeleteModel(
            name='data',
        ),
        migrations.AddField(
            model_name='lead_details',
            name='leadId',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.leads'),
        ),
        migrations.AddField(
            model_name='lead_assign_for_tc',
            name='Lead_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Telecaller.leads'),
        ),
        migrations.AddField(
            model_name='lead_assign_for_tc',
            name='Tc_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
    ]
