# Generated by Django 4.2.3 on 2023-11-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0003_remove_leads_assignto_tc_record_leads_call_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='Next_Update_Date',
            field=models.DateField(blank=True, default='', max_length=255, null=True),
        ),
    ]
