# Generated by Django 4.2.3 on 2023-11-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0010_employeeleave_leave_request_file'),
        ('Telecaller', '0003_lead_assign_for_tc_lead_details_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_assign_for_tc',
            name='lead_work_regId',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.workregister'),
        ),
    ]
