# Generated by Django 4.2.3 on 2023-11-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0011_leads_lead_details'),
        ('Telecaller', '0004_lead_assign_for_tc_lead_work_regid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='lead_collect_Emp_id',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='lead_work_regId',
        ),
        migrations.AlterField(
            model_name='lead_assign_for_tc',
            name='Lead_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads'),
        ),
        migrations.DeleteModel(
            name='lead_Details',
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
