# Generated by Django 4.2.3 on 2023-11-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0005_remove_leads_lead_collect_emp_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead_assign_for_TC',
        ),
    ]
