# Generated by Django 4.2.3 on 2023-11-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0011_leads_lead_details'),
        ('Telecaller', '0006_delete_lead_assign_for_tc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads_assignto_tc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Reason', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Assign_Date', models.DateField(auto_now=True, null=True)),
                ('Update_Action', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('TC_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('leadId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
    ]
