# Generated by Django 4.2.3 on 2023-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0007_alter_leads_assignto_tc_next_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads_assignto_tc',
            name='Next_Update_Date',
        ),
    ]
