# Generated by Django 4.2.3 on 2023-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='Update_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
