# Generated by Django 4.2.3 on 2023-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0008_leads_assignto_tc_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='Record',
            field=models.FileField(default='', upload_to='record'),
        ),
        migrations.AlterField(
            model_name='leads_assignto_tc',
            name='Update_Date',
            field=models.DateField(blank=True, default='', max_length=255, null=True),
        ),
    ]
