# Generated by Django 4.2.3 on 2023-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telecaller', '0009_leads_assignto_tc_next_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads_assignto_tc',
            name='Next_update_date',
            field=models.DateField(blank=True, default='1111-11-11', max_length=255, null=True),
        ),
    ]
